version: '3.3'

services:
  app:
    build:
      dockerfile: Dockerfile
      context: app

  prom:
    image: prom/prometheus:v2.27.1
    volumes:
      - ./prom/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./persistent/prometheus:/prometheus

  grafana:
    image: grafana/grafana:7.5.7
    ports:
      - 3000:3000
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/config.ini:/etc/grafana/config.ini
      - ./persistent/grafana_data:/var/lib/grafana

  telegraf:
    image: telegraf:1.8
    volumes:
      - ./monitor/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  nginx_metrics:
    image: nginx/nginx-prometheus-exporter:0.10.0
    command: -nginx.scrape-uri=http://app:80/stub_status3

  bot:
    build:
      dockerfile: Dockerfile
      context: bot
    volumes:
      - ./persistent/bot:/persistent/bot
